kiegroup/kie-cloud-tools

- rhba-dev-env/README.md
- rhba-dev-env/vagrant/provisioning/roles/setup_env/tasks/main.yml
See: https://issues.jboss.org/browse/KIECLOUD-295
Signed-off-by: Mauricio Magnani <mmagnani@redhat.com>
> [KIECLOUD-295] - Fix Cekit installation on kie-cloud-tools/rhba-dev-env

- cekit-cache-server/pom.xml
- cekit-cache-server/src/main/java/org/kie/cekit/cacher/builds/yaml/YamlFilesHelper.java
- cekit-cache-server/src/main/java/org/kie/cekit/cacher/builds/yaml/pojo/Modules.java
upgrade jacskon databind version
Signed-off-by: Filippe Spolti <fspolti@redhat.com>
> Add version field to yaml parser.

- cekit-cache-server/cekit-cacher-service.sh
- cekit-cache-server/cekit-cacher.service
- cekit-cache-server/src/main/java/org/kie/cekit/cacher/CacherLifecyle.java
- cekit-cache-server/src/main/java/org/kie/cekit/cacher/builds/github/GitRepository.java
include the files to configure rhel service.
Signed-off-by: Filippe Spolti <fspolti@redhat.com>
> fix git command for older git version.

- cekit-cache-server/cekit-cacher.service
Signed-off-by: Filippe Spolti <fspolti@redhat.com>
@errantepiphany little fix that @winklerm has spotted.
> fix service reload and stop commands, was missing the script path

- cekit-cache-server/Makefile
- cekit-cache-server/README.md
- cekit-cache-server/src/main/java/org/kie/cekit/cacher/builds/github/GitRepository.java
- cekit-cache-server/src/main/java/org/kie/cekit/cacher/builds/github/PullRequestAcceptor.java
- cekit-cache-server/src/test/java/org/kie/cekit/cacher/builds/github/PullRequestAcceptorTest.java
- cekit-cache-server/src/test/java/org/kie/cekit/cacher/properties/CacherPropertiesTest.java
- cekit-cache-server/src/test/java/org/kie/cekit/cacher/utils/CacherUtilsTest.java
> adjust the product renaming for 7.8.0

- cekit-helpers/cekit-image-validator/src/main/java/org/kie/cekit/image/validator/commands/SingleFileValidator.java
- cekit-helpers/cekit-image-validator/src/main/resources/application.properties
> remove leftovers

- rhba-dev-env/ansible/group_vars/all/vars_file.yml
- rhba-dev-env/ansible/roles/build_images/tasks/main.yml
See: https://issues.redhat.com/browse/KIECLOUD-409
Signed-off-by: Mauricio Magnani <msmagnanijr@gmail.com>
> [KIECLOUD-409] - Update rhba-dev-env project

- cekit-helpers/cekit-cache-server/README.md
- cekit-helpers/cekit-cache-server/src/main/java/org/kie/cekit/cacher/builds/github/GitRepository.java
- cekit-helpers/cekit-cache-server/src/main/java/org/kie/cekit/cacher/builds/github/PullRequestAcceptor.java
- cekit-helpers/cekit-cache-server/src/main/java/org/kie/cekit/cacher/builds/nightly/NightlyBuildsWatcher.java
- cekit-helpers/cekit-cache-server/src/main/java/org/kie/cekit/cacher/properties/CacherProperties.java
- cekit-helpers/cekit-cache-server/src/main/java/org/kie/cekit/cacher/utils/CacherUtils.java
> [KIECLOUD-410] - Create automated way to clean up ba cekit cacher

- cekit-helpers/cekit-cache-server/src/main/java/org/kie/cekit/cacher/builds/nightly/NightlyBuildsWatcher.java
- cekit-helpers/cekit-cache-server/src/main/java/org/kie/cekit/cacher/objects/PlainArtifact.java
- cekit-helpers/cekit-cache-server/src/main/java/org/kie/cekit/cacher/utils/CacherUtils.java
- cekit-helpers/cekit-cache-server/src/main/resources/META-INF/resources/list-artifacts.html
- cekit-helpers/cekit-cache-server/src/test/java/org/kie/cekit/cacher/builds/github/BuildUpdatesInterceptorTest.java
- cekit-helpers/cekit-cache-server/src/test/java/org/kie/cekit/cacher/builds/github/PullRequestAcceptorTest.java
> [KIECLOUD-429] - Add timestamp info on the cacher artifacts

- cekit-helpers/cekit-cache-server/src/main/java/org/kie/cekit/cacher/builds/github/PullRequestAcceptor.java
- cekit-helpers/cekit-cache-server/src/test/java/org/kie/cekit/cacher/builds/github/PullRequestAcceptorTest.java
See: https://issues.redhat.com/browse/KIECLOUD-453
> [KIECLOUD-453] - Use unique names for product artifacts

- cekit-helpers/cekit-cache-server/src/main/java/org/kie/cekit/cacher/builds/github/PullRequestAcceptor.java
- cekit-helpers/cekit-cache-server/src/test/java/org/kie/cekit/cacher/builds/github/PullRequestAcceptorTest.java
Address second part of the issue, add product id as part of the artifact name
> [KIECLOUD-453] - Adapt product artifacts definitions to CPaaS build

- cekit-helpers/cekit-cache-server/src/main/java/org/kie/cekit/cacher/builds/cr/CRBuildsPullRequestAcceptor.java
- cekit-helpers/cekit-cache-server/src/main/java/org/kie/cekit/cacher/builds/github/GitRepository.java
- cekit-helpers/cekit-cache-server/src/main/java/org/kie/cekit/cacher/builds/nightly/NightlyBuildsPullRequestAcceptor.java
- cekit-helpers/cekit-cache-server/src/main/java/org/kie/cekit/cacher/builds/nightly/NightlyBuildsWatcher.java
- cekit-helpers/cekit-cache-server/src/main/java/org/kie/cekit/cacher/properties/CacherProperties.java
- cekit-helpers/cekit-cache-server/src/main/java/org/kie/cekit/cacher/utils/BuildUtils.java
- cekit-helpers/cekit-cache-server/src/main/java/org/kie/cekit/cacher/utils/CacherUtils.java
- cekit-helpers/cekit-cache-server/src/main/resources/application.properties
- cekit-helpers/cekit-cache-server/src/test/java/org/kie/cekit/cacher/builds/github/NightlyBuildsPullRequestAcceptorTest.java
- cekit-helpers/cekit-cache-server/src/test/java/org/kie/cekit/cacher/properties/CacherPropertiesTest.java
- cekit-helpers/pom.xml
> [KIECLOUD-500] - Apply the new build date format on CeKit cacher

- cekit-helpers/cekit-cache-server/src/main/java/org/kie/cekit/cacher/builds/github/GitRepository.java
- cekit-helpers/cekit-cache-server/src/main/java/org/kie/cekit/cacher/utils/BuildUtils.java
- cekit-helpers/pom.xml
> [KIECLOUD-521] - Cekit Cacher is not recognizing the new date format

- cekit-helpers/cekit-cache-server/README.md
- cekit-helpers/cekit-cache-server/pom.xml
- cekit-helpers/cekit-cache-server/src/main/java/org/kie/cekit/cacher/objects/CacherUploadedFile.java
- cekit-helpers/cekit-cache-server/src/main/java/org/kie/cekit/cacher/resources/CacherResource.java
- cekit-helpers/cekit-cache-server/src/main/java/org/kie/cekit/cacher/utils/CacherUtils.java
- cekit-helpers/cekit-cache-server/src/main/resources/META-INF/resources/index.html
- cekit-helpers/cekit-cache-server/src/main/resources/application.properties
- cekit-helpers/cekit-cache-server/src/test/java/org/kie/cekit/cacher/builds/github/NightlyBuildsPullRequestAcceptorTest.java
- cekit-helpers/cekit-cache-server/src/test/java/org/kie/cekit/cacher/resources/CacherResourceEndpointTest.java
> [KIECLOUD-485] - Add option to upload files to the cekit-cacher

- cekit-helpers/cekit-cache-server/src/main/java/org/kie/cekit/cacher/builds/cr/CRBuildsPullRequestAcceptor.java
- cekit-helpers/cekit-cache-server/src/main/java/org/kie/cekit/cacher/builds/nightly/NightlyBuildsPullRequestAcceptor.java
- cekit-helpers/cekit-cache-server/src/main/java/org/kie/cekit/cacher/properties/CacherProperties.java
- cekit-helpers/cekit-cache-server/src/main/java/org/kie/cekit/cacher/utils/BuildUtils.java
- cekit-helpers/cekit-cache-server/src/main/resources/META-INF/resources/cekit-cacher.properties
> fix cr builds update

- cekit-helpers/cekit-cache-server/Makefile
- cekit-helpers/cekit-cache-server/src/main/java/org/kie/cekit/cacher/builds/github/GitRepository.java
- cekit-helpers/cekit-cache-server/src/main/java/org/kie/cekit/cacher/builds/nightly/NightlyBuildsWatcher.java
- cekit-helpers/cekit-cache-server/src/test/java/org/kie/cekit/cacher/builds/github/NightlyBuildsPullRequestAcceptorTest.java
- cekit-helpers/cekit-cache-server/src/test/java/org/kie/cekit/cacher/builds/yaml/YamlFilesLoaderTest.java
- cekit-helpers/cekit-cache-server/src/test/java/org/kie/cekit/cacher/properties/CacherPropertiesTest.java
- cekit-helpers/cekit-cache-server/src/test/resources/modules.yaml
> [KIECLOUD-607] - Update cekit-cacher with the single product updates

- cekit-helpers/cekit-cache-server/pom.xml
- cekit-helpers/cekit-image-descriptors/pom.xml
- cekit-helpers/cekit-image-validator/pom.xml
- cekit-helpers/pom.xml
Reverts kiegroup/kie-cloud-tools#61
> Revert "Prepare 1.3.2 release and next iteration"

- cekit-helpers/cekit-image-descriptors/src/main/java/org/kie/cekit/image/descriptors/common/Run.java
- cekit-helpers/pom.xml
Signed-off-by: Your Name <fspolti@redhat.com>
> [KOGITO-8472] - CeKit Validator Unrecognized field entrypoint

- cekit-helpers/cekit-cache-server/Makefile
- cekit-helpers/cekit-cache-server/README.md
- cekit-helpers/cekit-cache-server/src/main/java/org/kie/cekit/cacher/builds/cr/CRBuildInterceptor.java
- cekit-helpers/cekit-cache-server/src/main/java/org/kie/cekit/cacher/builds/cr/CRBuildsUpdater.java
- cekit-helpers/cekit-cache-server/src/main/java/org/kie/cekit/cacher/builds/github/GitRepository.java
- cekit-helpers/cekit-cache-server/src/main/java/org/kie/cekit/cacher/builds/github/PullRequestSender.java
- cekit-helpers/cekit-cache-server/src/main/java/org/kie/cekit/cacher/builds/nightly/NightlyBuildsPullRequestAcceptor.java
- cekit-helpers/cekit-cache-server/src/main/java/org/kie/cekit/cacher/properties/CacherProperties.java
- cekit-helpers/cekit-cache-server/src/test/java/org/kie/cekit/cacher/builds/github/GitRepositoryTest.java
- cekit-helpers/cekit-cache-server/src/test/java/org/kie/cekit/cacher/builds/github/NightlyBuildsPullRequestAcceptorTest.java
- cekit-helpers/cekit-cache-server/src/test/java/org/kie/cekit/cacher/builds/yaml/YamlFilesLoaderTest.java
> remove rhdm methods from cacher

- cekit-helpers/cekit-image-descriptors/src/main/java/org/kie/cekit/image/descriptors/common/Port.java
Signed-off-by: Your Name <fspolti@redhat.com>
> [KOGITO-8509] - CeKit Validator Unrecognized field service

- cekit-helpers/cekit-image-descriptors/src/main/java/org/kie/cekit/image/descriptors/module/Artifact.java
Following https://docs.cekit.io/en/latest/descriptor/image.html#image-source-artifacts
> Corrected Artifact specification
